server:
  port: 8080
  servlet:
    context-path: "/ss"


mybatis:
  mapperLocations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sharding_db?serverTimezone=UTC
    username: root
    password: root

logging:
  level:
    org.pismery.javacourse.ss.homework: debug