server:
  port: 9090
  servlet:
    context-path: /redis-lock
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 1000ms
    connect-timeout: 1000ms
    jedis:
      pool:
        max-active: 9
        max-idle: 9
        max-wait: 1s
        min-idle: 1
        time-between-eviction-runs: 100ms
    lettuce:
      pool:
        max-active: 9
        max-idle: 9
        max-wait: 1s
        min-idle: 1
        time-between-eviction-runs: 100ms



