

primary.datasource:
  url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
  username: root
  password:

secondary.datasource:
  [
    {
      url: "jdbc:mysql://localhost:3307/test?serverTimezone=UTC",
      username: root,
      password:
    },
    {
      url: "jdbc:mysql://localhost:3307/test?serverTimezone=UTC",
      username: root,
      password:
    }
  ]

server:
  port: 8080
  servlet:
    context-path: "/database"

logging:
  level:
    org.pismery.javacourse.database.homework: debug
    org.apache.shardingsphere: debug
